<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

    <PublishAOT>true</PublishAOT>
    <!-- 开启单文件发布 -->
    <PublishSingleFile>true</PublishSingleFile>
    <!-- 核心：将原生库也打包进单文件中（运行时会自动解压到临时目录） -->
    <IncludeNativeLibrariesForExtract>true</IncludeNativeLibrariesForExtract>
    <!-- 可选：压缩单文件体积 -->
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="output\**" />
    <EmbeddedResource Remove="output\**" />
    <None Remove="output\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="sample-fd3.bin" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OpenTK" Version="4.9.4" />
    <PackageReference Include="SkiaSharp" Version="4.147.0-preview.2.1" />
  </ItemGroup>

  <ItemGroup>
    <TrimmerRootAssembly Include="OpenTK.Windowing.Desktop" />
  </ItemGroup>

</Project>